export type RecoveryPolicy = {
  area: string;
  action: string;
  auditActions: string[];
  normalUserCopy: string;
  behavior: "edit" | "correct" | "reverse" | "void" | "archive" | "close" | "draft-delete";
  reasonRequired: boolean;
  preservesHistory: boolean;
  notes?: string;
};

export const RECOVERY_POLICIES: RecoveryPolicy[] = [
  {
    area: "payments",
    action: "payment-created",
    auditActions: ["PAYMENT_CREATED"],
    normalUserCopy: "Encaissement tracable",
    behavior: "reverse",
    reasonRequired: true,
    preservesHistory: true,
    notes: "Original payment stays in the ledger; mistakes are handled by correction or reversal rows.",
  },
  {
    area: "payments",
    action: "payment-corrected",
    auditActions: ["PAYMENT_CORRECTED"],
    normalUserCopy: "Correction avec motif",
    behavior: "correct",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "payments",
    action: "payment-reversed",
    auditActions: ["PAYMENT_REVERSED", "PAYMENT_DELETED"],
    normalUserCopy: "Annulation tracable",
    behavior: "reverse",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "receipts",
    action: "receipt-issued",
    auditActions: ["RECEIPT_ISSUED", "RECEIPT_EMAIL_SENT", "RECEIPT_EMAIL_FAILED"],
    normalUserCopy: "Recu emis",
    behavior: "void",
    reasonRequired: true,
    preservesHistory: true,
    notes: "Issued receipts are official snapshots; failed/sent email delivery is audit history, not receipt mutation.",
  },
  {
    area: "receipts",
    action: "receipt-voided",
    auditActions: ["RECEIPT_VOIDED"],
    normalUserCopy: "Recu annule",
    behavior: "void",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "enrollment",
    action: "enrollment-applied",
    auditActions: ["ENROLLMENT_APPLIED"],
    normalUserCopy: "Inscription enregistree",
    behavior: "void",
    reasonRequired: true,
    preservesHistory: true,
    notes: "Enrollment recovery should keep created business rows traceable through reversal, void, cancel, close, or archive.",
  },
  {
    area: "enrollment",
    action: "enrollment-voided",
    auditActions: ["ENROLLMENT_VOIDED", "ENROLLMENT_REVERTED"],
    normalUserCopy: "Inscription annulee",
    behavior: "void",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "members",
    action: "member-created",
    auditActions: ["MEMBER_CREATED"],
    normalUserCopy: "Eleve cree",
    behavior: "archive",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "members",
    action: "member-archived",
    auditActions: ["MEMBER_ARCHIVED"],
    normalUserCopy: "Eleve archive",
    behavior: "archive",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "members",
    action: "member-updated",
    auditActions: ["MEMBER_UPDATED"],
    normalUserCopy: "Fiche eleve modifiee",
    behavior: "edit",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "members",
    action: "legacy-member-deleted",
    auditActions: ["MEMBER_DELETED"],
    normalUserCopy: "Ancienne suppression eleve",
    behavior: "archive",
    reasonRequired: false,
    preservesHistory: true,
    notes: "Kept for old audit presentation; current member delete routes archive instead.",
  },
  {
    area: "subscriptions",
    action: "subscription-created",
    auditActions: ["MEMBER_SUBSCRIPTION_CREATED"],
    normalUserCopy: "Abonnement cree",
    behavior: "correct",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "subscriptions",
    action: "subscription-updated",
    auditActions: ["MEMBER_SUBSCRIPTION_UPDATED"],
    normalUserCopy: "Abonnement corrige",
    behavior: "correct",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "subscriptions",
    action: "subscription-cancelled",
    auditActions: ["MEMBER_SUBSCRIPTION_CANCELLED"],
    normalUserCopy: "Abonnement resilie",
    behavior: "void",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "group-members",
    action: "assignment-closed",
    auditActions: ["GROUP_MEMBER_CLOSED", "GROUP_MEMBERS_CLOSED"],
    normalUserCopy: "Affectation fermee",
    behavior: "close",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "groups",
    action: "group-deactivated",
    auditActions: ["GROUP_DEACTIVATED"],
    normalUserCopy: "Cours desactive",
    behavior: "archive",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "groups",
    action: "group-coach-propagated",
    auditActions: ["GROUP_COACH_PROPAGATED", "COACH_SPORT_OVERRIDE_USED"],
    normalUserCopy: "Coach du cours modifie",
    behavior: "correct",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "group-schedules",
    action: "group-schedule-created",
    auditActions: ["GROUP_SCHEDULE_CREATED"],
    normalUserCopy: "Horaire ajoute",
    behavior: "close",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "group-schedules",
    action: "group-schedule-closed",
    auditActions: ["GROUP_SCHEDULE_CLOSED"],
    normalUserCopy: "Horaire retire",
    behavior: "close",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "group-schedules",
    action: "group-schedule-updated",
    auditActions: ["GROUP_SCHEDULE_UPDATED"],
    normalUserCopy: "Horaire modifie",
    behavior: "close",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "schedule-templates",
    action: "schedule-template-changed",
    auditActions: ["SCHEDULE_TEMPLATE_CREATED", "SCHEDULE_TEMPLATE_UPDATED", "SCHEDULE_TEMPLATE_APPLIED"],
    normalUserCopy: "Modele horaire modifie",
    behavior: "edit",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "schedule-templates",
    action: "schedule-template-archived",
    auditActions: ["SCHEDULE_TEMPLATE_ARCHIVED"],
    normalUserCopy: "Modele horaire archive",
    behavior: "archive",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "sessions",
    action: "session-cancelled",
    auditActions: ["SESSION_CANCELLED"],
    normalUserCopy: "Seance annulee",
    behavior: "void",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "sessions",
    action: "session-updated",
    auditActions: ["SESSION_UPDATED", "SESSION_POSTPONED", "SESSION_COMPLETED", "SESSION_REOPENED"],
    normalUserCopy: "Seance corrigee",
    behavior: "correct",
    reasonRequired: false,
    preservesHistory: true,
    notes: "Future UX should ask for a reason on broad permanent changes.",
  },
  {
    area: "sessions",
    action: "sessions-generated",
    auditActions: ["SESSIONS_GENERATED"],
    normalUserCopy: "Seances generees",
    behavior: "draft-delete",
    reasonRequired: false,
    preservesHistory: true,
    notes: "Generation is previewed before confirmation; generated sessions can be cancelled or edited before pointage.",
  },
  {
    area: "attendance",
    action: "attendance-created",
    auditActions: ["ATTENDANCE_CREATED"],
    normalUserCopy: "Pointage enregistre",
    behavior: "correct",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "attendance",
    action: "attendance-corrected",
    auditActions: ["ATTENDANCE_UPDATED"],
    normalUserCopy: "Pointage corrige",
    behavior: "correct",
    reasonRequired: true,
    preservesHistory: true,
  },
  {
    area: "attendance",
    action: "attendance-cancelled",
    auditActions: ["ATTENDANCE_DELETED"],
    normalUserCopy: "Pointage annule",
    behavior: "correct",
    reasonRequired: true,
    preservesHistory: true,
    notes: "The row is still physically removed; audit details preserve the previous pointage until an append-only schema pass.",
  },
  {
    area: "catalog",
    action: "catalog-deactivated",
    auditActions: ["SPORT_DEACTIVATED", "COACH_DEACTIVATED", "SUBSCRIPTION_PLAN_DEACTIVATED", "OFFER_DEACTIVATED"],
    normalUserCopy: "Catalogue desactive",
    behavior: "archive",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "catalog",
    action: "offer-created",
    auditActions: ["OFFER_CREATED"],
    normalUserCopy: "Offre creee",
    behavior: "edit",
    reasonRequired: false,
    preservesHistory: true,
    notes: "Used offers should be deactivated and recreated instead of edited in place.",
  },
  {
    area: "settings",
    action: "settings-updated",
    auditActions: ["CLUB_SETTINGS_UPDATED", "USER_CREATED", "USER_UPDATED", "USER_REGISTERED", "ACCOUNT_UPDATED", "ADMIN_BOOTSTRAPPED"],
    normalUserCopy: "Parametres modifies",
    behavior: "edit",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "settings",
    action: "password-reset",
    auditActions: ["PASSWORD_RESET_REQUESTED", "PASSWORD_RESET_SENT_BY_ADMIN", "PASSWORD_RESET_COMPLETED"],
    normalUserCopy: "Mot de passe gere",
    behavior: "edit",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "data-import",
    action: "data-import-applied",
    auditActions: ["DATA_IMPORT_APPLIED"],
    normalUserCopy: "Import applique",
    behavior: "draft-delete",
    reasonRequired: false,
    preservesHistory: true,
    notes: "Rollback is only safe before imported rows receive later business activity.",
  },
  {
    area: "data-import",
    action: "data-import-rolled-back",
    auditActions: ["DATA_IMPORT_ROLLED_BACK"],
    normalUserCopy: "Import annule",
    behavior: "draft-delete",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "payments",
    action: "payment-reminder",
    auditActions: ["PAYMENT_REMINDER_SENT"],
    normalUserCopy: "Relance paiement",
    behavior: "edit",
    reasonRequired: false,
    preservesHistory: true,
  },
  {
    area: "catalog",
    action: "unused-draft-removed",
    auditActions: [],
    normalUserCopy: "Brouillon supprime",
    behavior: "draft-delete",
    reasonRequired: false,
    preservesHistory: false,
  },
];

export function policyForAction(action: string): RecoveryPolicy | null {
  return RECOVERY_POLICIES.find((policy) => policy.action === action || policy.auditActions.includes(action)) ?? null;
}

export function policyForAuditAction(action: string): RecoveryPolicy | null {
  return policyForAction(action);
}
